spring.application.name=event-registration
server.port=${PORT:8084}

# MySQL Database Connection (Cloud or Local)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/event_registration_portal}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Maesecret@99sql}

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka Configuration
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:https://eureka-service-s7wp.onrender.com/eureka/}

# JWT Configuration (Must match Auth Service exactly)
college.app.jwtSecret=${JWT_SECRET:}
college.app.jwtExpirationMs=86400000
